### PR TITLE
Add markdown-classes plugin

### PR DESCRIPTION
**Pull request by m2de**

### CODE REVIEW

**Comment by m2de** [comment]
Hi @ulivz ... for sure ... not being lazy here but to save re-typing, I have a post explaining the reasons for the code here: https://www.marcomark.net/code/vuepress/markdown-classes.html

**Comment by ulivz** [comment]
Got it, thanks. I just want to all the plugins in this list are carefully created and can really solve problems in certain scenarios.

**Comment by ulivz** [comment]
BTW, I just check your README but cannot find the link of this post, the better is to add it so that users can be closer to this plugin.

**Comment by m2de** [comment]
Thanks @ulivz . Appreciate the feedback and your desire to maintain a reputable list! Thanks for your work.

**Pull request merged**
